public with sharing class FinalSanctionWrapper {
    @AuraEnabled
    public string propid{get;set;}

    @AuraEnabled
    public string aclandare{get;set;}
     @AuraEnabled
    public string lclandare{get;set;}   
     @AuraEnabled
    public string propNameLandArea{get;set;}
     @AuraEnabled
    public string resultLandArea{get;set;}

     @AuraEnabled
    public string propNameTitleDeedNumber{get;set;}
     @AuraEnabled
    public string resultTitleDeedNumber{get;set;}
      @AuraEnabled
    public string actitledeedno{get;set;}
        @AuraEnabled
    public string lctitledeedno{get;set;}

     @AuraEnabled
    public string propNameTitledeedtype{get;set;}
     @AuraEnabled
    public string resultTitledeedtype{get;set;}
     @AuraEnabled
    public string actitledeedtype{get;set;}
     @AuraEnabled
    public string lctitledeedtype{get;set;}
    
     @AuraEnabled
    public string propNametitledate{get;set;}
     @AuraEnabled
    public string actitledate{get;set;}
        @AuraEnabled
    public string lctitledate{get;set;}
     @AuraEnabled
    public string resultTitleDeeddate{get;set;}
    
   
     
   
}